In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
df = df[['Pclass','Name','Sex','Age','Embarked','Survived']]

In [ ]:
df.shape

(891, 6)

In [ ]:
df.head()

Pclass                                               Name     Sex   Age  \
0       3                            Braund, Mr. Owen Harris    male  22.0   
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2       3                             Heikkinen, Miss. Laina  female  26.0   
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4       3                           Allen, Mr. William Henry    male  35.0   

  Embarked  Survived  
0        S         0  
1        C         1  
2        S         1  
3        S         1  
4        S         0

In [ ]:
df.info

<bound method DataFrame.info of      Pclass                                               Name     Sex   Age  \
0         3                            Braund, Mr. Owen Harris    male  22.0   
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2         3                             Heikkinen, Miss. Laina  female  26.0   
3         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4         3                           Allen, Mr. William Henry    male  35.0   
..      ...                                                ...     ...   ...   
886       2                              Montvila, Rev. Juozas    male  27.0   
887       1                       Graham, Miss. Margaret Edith  female  19.0   
888       3           Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
889       1                              Behr, Mr. Karl Howell    male  26.0   
890       3                                Dooley, Mr. Patrick    male  32.0   

    Embarked  Survived  
0          S         0  
1          C         1  
2          S         1  
3          S         1  
4          S         0  
..       ...       ...  
886        S         0  
887        S         1  
888        S         0  
889        C         1  
890        Q         0  

[891 rows x 6 columns]>

In [ ]:
df.isnull().sum()

Pclass        0
Name          0
Sex           0
Age         177
Embarked      2
Survived      0
dtype: int64

In [ ]:
df = df.dropna()
df.isnull().sum()

Pclass      0
Name        0
Sex         0
Age         0
Embarked    0
Survived    0
dtype: int64

In [ ]:
df['Name'].unique()

array(['Braund, Mr. Owen Harris',
       'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
       'Heikkinen, Miss. Laina',
       'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
       'Allen, Mr. William Henry', 'McCarthy, Mr. Timothy J',
       'Palsson, Master. Gosta Leonard',
       'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
       'Nasser, Mrs. Nicholas (Adele Achem)',
       'Sandstrom, Miss. Marguerite Rut', 'Bonnell, Miss. Elizabeth',
       'Saundercock, Mr. William Henry', 'Andersson, Mr. Anders Johan',
       'Vestrom, Miss. Hulda Amanda Adolfina',
       'Hewlett, Mrs. (Mary D Kingcome) ', 'Rice, Master. Eugene',
       'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
       'Fynney, Mr. Joseph J', 'Beesley, Mr. Lawrence',
       'McGowan, Miss. Anna "Annie"', 'Sloper, Mr. William Thompson',
       'Palsson, Miss. Torborg Danira',
       'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
       'Fortune, Mr. Charles Alexander', 'Uruchurtu

In [ ]:
from sklearn.preprocessing import LabelEncoder
le_country = LabelEncoder()

In [ ]:
df['Name'] = le_country.fit_transform(df['Name'])
df['Name'].unique()

<ipython-input-30-7404ac142d3c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Name'] = le_country.fit_transform(df['Name'])


array([103, 179, 317, 247,  15, 440, 509, 368, 473, 582,  94, 584,  28,
       673, 322, 554, 672, 248,  79, 442, 612, 511,  44, 238, 661, 687,
       450, 335, 126, 670, 485,   7, 660, 394, 198,  38, 514, 490, 301,
       228, 506, 574, 491, 684, 270, 599, 304, 604, 492, 174,  25, 385,
       354, 271, 339, 151,  86, 458, 120, 208, 675, 590, 132, 346,  52,
       233, 237, 140, 149,  31, 141, 196, 173, 263, 279, 204, 376, 533,
       689, 361, 283, 456, 580, 547, 542, 705,  67, 371,  46, 526, 167,
       659,  69,  24, 325, 472, 680, 688, 484, 429, 219, 210, 154, 565,
       682, 616, 557, 481, 246, 504, 255, 493, 288, 110,  32, 482,  29,
       232, 477, 115,  68, 525, 448, 711, 696, 260, 170, 175, 679,  81,
       122, 513, 264, 609, 417, 665, 552, 364, 601, 615, 388, 348, 289,
       406,  41,  75, 386, 567,  97, 656, 540, 127,  20, 476, 107, 426,
       498, 704, 667, 359, 703, 155, 629,  51,   9, 131,  93,  12, 124,
       530, 261, 478, 338, 349,  71, 305, 631, 101, 277, 341,  8

In [ ]:
df['Sex'] = le_country.fit_transform(df['Sex'])
df['Sex'].unique()

<ipython-input-31-afb583198a78>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sex'] = le_country.fit_transform(df['Sex'])


array([1, 0])

In [ ]:
df['Embarked'] = le_country.fit_transform(df['Embarked'])
df['Embarked'].unique()

<ipython-input-32-dfeab2faa02f>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Embarked'] = le_country.fit_transform(df['Embarked'])


array([2, 0, 1])

In [ ]:
df.sample()

Pclass  Name  Sex   Age  Embarked  Survived
843       3   404    1  34.5         0         0

In [ ]:
df.head()

Pclass  Name  Sex   Age  Embarked  Survived
0       3   103    1  22.0         2         0
1       1   179    0  38.0         0         1
2       3   317    0  26.0         2         1
3       1   247    0  35.0         2         1
4       3    15    1  35.0         2         0

In [ ]:
#defining input columns
X = df[['Pclass',	'Name','Sex','Age','Embarked']]
X

Pclass  Name  Sex   Age  Embarked
0         3   103    1  22.0         2
1         1   179    0  38.0         0
2         3   317    0  26.0         2
3         1   247    0  35.0         2
4         3    15    1  35.0         2
..      ...   ...  ...   ...       ...
885       3   556    0  39.0         1
886       2   460    1  27.0         2
887       1   274    0  19.0         2
889       1    80    1  26.0         0
890       3   205    1  32.0         1

[712 rows x 5 columns]

In [ ]:
y = df[['Survived']]
y

Survived
0           0
1           1
2           1
3           1
4           0
..        ...
885         0
886         0
887         1
889         1
890         0

[712 rows x 1 columns]